### ISSUE TITLE
Parser fails on values with dimensions

### ISSUE THREAD

**Issue by stephen-hawley** [Redth/Svg2VectorDrawable.Net#5]
Generate an svg file with InkScape and save as "plain svg". By default, you will get dimensions in the header. This crashes with a `FormatException` on parse:
```
Severity	Code	Description	Project	File	Line	Suppression State
Error	MAUI0000	System.FormatException: Input string was not in a correct format.
   at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Svg2VectorDrawable.Svg2Vector.ParseDimension(SvgTree avg, XmlNode nNode) in /Users/runner/work/Svg2VectorDrawable.Net/Svg2VectorDrawable.Net/Svg2VectorDrawable.Net/Svg2Vector.cs:line 247
   at Svg2VectorDrawable.Svg2Vector.Parse(String file) in /Users/runner/work/Svg2VectorDrawable.Net/Svg2VectorDrawable.Net/Svg2VectorDrawable.Net/Svg2Vector.cs:line 95
   at Svg2VectorDrawable.Svg2Vector.ParseSvgToXml(String inputSvgFilename, Stream outputStream) in /Users/runner/work/Svg2VectorDrawable.Net/Svg2VectorDrawable.Net/Svg2VectorDrawable.Net/Svg2Vector.cs:line 773
   at Svg2VectorDrawable.Svg2Vector.Convert(String inputSvgFilename, String outputXmlFilename) in /Users/runner/work/Svg2VectorDrawable.Net/Svg2VectorDrawable.Net/Svg2VectorDrawable.Net/Svg2Vector.cs:line 759
   at Microsoft.Maui.Resizetizer.AndroidAdaptiveIconGenerator.Generate() in D:\a\1\s\src\SingleProject\Resizetizer\src\AndroidAdaptiveIconGenerator.cs:line 73
   at Microsoft.Maui.Resizetizer.ResizetizeImages.ProcessAppIcon(ResizeImageInfo img, ConcurrentBag`1 resizedImages) in D:\a\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 132
   at Microsoft.Maui.Resizetizer.ResizetizeImages.<>c__DisplayClass26_0.<ExecuteAsync>b__0(ResizeImageInfo img) in D:\a\1\s\src\SingleProject\Resizetizer\src\ResizetizeImages.cs:line 88
   at Microsoft.Maui.Resizetizer.AsyncTaskExtensions.<>c__DisplayClass0_0`1.<ParallelForEach>b__0(TSource s) in D:\a\1\s\src\SingleProject\Resizetizer\src\AsyncTaskExtensions.cs:line 21	Cthulr	C:\Users\sthawl\.nuget\packages\microsoft.maui.resizetizer.sdk\6.0.101-preview.10.2068\build\Microsoft.Maui.Resizetizer.Sdk.targets	463	
```
The issue is in the header of the file looks like this:
```
<svg
   width="210mm"
   height="297mm"
   viewBox="0 0 210 297"
   version="1.1"
   id="svg5"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:svg="http://www.w3.org/2000/svg">
```
`ParseDimensions` assumes that the dimensions end in either `%` or `px`, but svg has a fairly long list of possible dimensions that can be appended to a number. It should be noted that a floating point number can have an exponent on it so looking for the first non numeric/sign/decimal is complicated by that. Probably the way to do this is to step back from the end of string finding the range of alphabetical characters and chop those off.

**Comment by irongut** [comment]
I've just fallen foul of the same issue using .NET MAUI Preview 10 to create an app icon. My SVG has height and width specified as `256pt` which is valid SVG and Android Studio is able to create a vector drawable icon from it but Svg2VectorDrawable.Net
 is not.
